-- =====================================================================
-- V1 — Schéma initial (base neuve)
-- Généré depuis les entités JPA (Hibernate 7 / dialecte PostgreSQL).
-- Toute évolution ultérieure du schéma passe par une nouvelle migration Vn.
-- Avec spring.jpa.hibernate.ddl-auto=validate, ce script doit rester
-- strictement aligné sur les entités.
-- =====================================================================

create table etablissements (
    id bigint generated by default as identity,
    nom varchar(150) not null,
    code varchar(50) not null unique,
    email_contact varchar(100),
    telephone varchar(30),
    adresse varchar(255),
    statut varchar(20) not null check ((statut in ('ACTIF','SUSPENDU','CLOTURE'))),
    plan_tarifaire varchar(50),
    date_expiration_abonnement timestamp(6),
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id)
);

create table roles (
    id integer generated by default as identity,
    nom varchar(50) not null unique,
    primary key (id)
);

create table niveaux (
    id integer generated by default as identity,
    nom varchar(50) not null unique,
    primary key (id)
);

create table utilisateurs (
    id bigint generated by default as identity,
    username varchar(50) not null unique,
    email varchar(100) unique,
    mot_de_passe varchar(255) not null,
    role_id integer not null,
    etablissement_id bigint,
    est_actif boolean,
    est_premier_login boolean,
    otp_code varchar(10),
    otp_expiry timestamp(6),
    otp_tentatives integer,
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id)
);

create table profils (
    id bigint generated by default as identity,
    utilisateur_id bigint unique,
    prenom varchar(100) not null,
    nom varchar(100) not null,
    telephone varchar(20),
    email varchar(150),
    photo_url TEXT,
    genre varchar(10),
    date_naissance date,
    adresse TEXT,
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id)
);

create table password_reset_tokens (
    id bigint generated by default as identity,
    token varchar(255) not null unique,
    utilisateur_id bigint not null,
    expiry_date timestamp(6) not null,
    est_utilise boolean not null,
    primary key (id)
);

create table parents (
    id bigint generated by default as identity,
    profil_id bigint not null unique,
    etablissement_id bigint,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table enseignants (
    id bigint generated by default as identity,
    profil_id bigint not null unique,
    matricule varchar(50) not null unique,
    biographie TEXT,
    etablissement_id bigint,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table classes (
    id bigint generated by default as identity,
    nom varchar(50) not null,
    niveau_id integer not null,
    etablissement_id bigint,
    capacite_max integer not null,
    enseignant_principal_id bigint,
    annee_scolaire varchar(20) not null,
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id)
);

create table eleves (
    id bigint generated by default as identity,
    profil_id bigint not null unique,
    matricule varchar(50) not null unique,
    classe_id bigint,
    parent_id bigint,
    parent_secondaire_id bigint,
    etablissement_id bigint,
    statut varchar(20),
    date_creation timestamp(6) not null,
    primary key (id)
);

create table matieres (
    id bigint generated by default as identity,
    nom varchar(100) not null,
    code varchar(20) not null unique,
    etablissement_id bigint,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table classes_matieres (
    id bigint generated by default as identity,
    classe_id bigint not null,
    matiere_id bigint not null,
    enseignant_id bigint,
    etablissement_id bigint,
    coefficient float(53) not null,
    primary key (id),
    unique (classe_id, matiere_id)
);

create table notes (
    id bigint generated by default as identity,
    eleve_id bigint not null,
    classe_matiere_id bigint not null,
    etablissement_id bigint,
    periode varchar(20) not null,
    type_evaluation varchar(50) not null,
    valeur float(53) not null,
    note_max float(53),
    appreciation TEXT,
    cree_par bigint,
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id)
);

create table bulletins (
    id bigint generated by default as identity,
    eleve_id bigint not null,
    classe_id bigint not null,
    etablissement_id bigint,
    periode varchar(20) not null,
    annee_scolaire varchar(20) not null,
    moyenne_generale float(53),
    appreciation_generale TEXT,
    est_verrouille boolean not null,
    date_creation timestamp(6) not null,
    date_modification timestamp(6) not null,
    primary key (id),
    unique (eleve_id, periode, annee_scolaire)
);

create table presences (
    id bigint generated by default as identity,
    eleve_id bigint not null,
    classe_matiere_id bigint,
    etablissement_id bigint,
    date date not null,
    statut varchar(20) not null,
    est_justifie boolean,
    notes_justification TEXT,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table presences_enseignants (
    id bigint generated by default as identity,
    enseignant_id bigint not null,
    etablissement_id bigint,
    date date not null,
    statut varchar(20) not null,
    heure_arrivee varchar(10),
    heure_depart varchar(10),
    remarques TEXT,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table frais_scolarite (
    id bigint generated by default as identity,
    classe_id bigint not null,
    etablissement_id bigint,
    titre varchar(100) not null,
    montant float(53) not null,
    date_echeance date not null,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table paiements (
    id bigint generated by default as identity,
    eleve_id bigint not null,
    frais_id bigint,
    etablissement_id bigint,
    montant_paye float(53) not null,
    mode_paiement varchar(50) not null,
    reference_transaction varchar(100),
    numero_recu varchar(100) not null unique,
    recu_par bigint,
    date_paiement timestamp(6) not null,
    primary key (id)
);

create table emplois_du_temps (
    id bigint generated by default as identity,
    classe_matiere_id bigint,
    classe_id bigint,
    etablissement_id bigint,
    type_creneau varchar(30),
    libelle_pause varchar(100),
    jour_semaine integer not null,
    heure_debut time(0) not null,
    heure_fin time(0) not null,
    salle varchar(50),
    primary key (id)
);

create table notifications (
    id bigint generated by default as identity,
    expediteur_id bigint,
    destinataire_id bigint not null,
    etablissement_id bigint,
    titre varchar(150) not null,
    contenu TEXT not null,
    est_lu boolean,
    date_creation timestamp(6) not null,
    primary key (id)
);

create table journaux_activites (
    id bigint generated by default as identity,
    utilisateur_id bigint,
    etablissement_id bigint,
    action varchar(100) not null,
    description TEXT,
    adresse_ip varchar(45),
    date_creation timestamp(6) not null,
    primary key (id)
);

-- ---------------------------------------------------------------------
-- Clés étrangères
-- ---------------------------------------------------------------------
alter table if exists utilisateurs add constraint fk_utilisateurs_role foreign key (role_id) references roles;
alter table if exists utilisateurs add constraint fk_utilisateurs_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists profils add constraint fk_profils_utilisateur foreign key (utilisateur_id) references utilisateurs;
alter table if exists password_reset_tokens add constraint fk_prt_utilisateur foreign key (utilisateur_id) references utilisateurs;
alter table if exists parents add constraint fk_parents_profil foreign key (profil_id) references profils;
alter table if exists parents add constraint fk_parents_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists enseignants add constraint fk_enseignants_profil foreign key (profil_id) references profils;
alter table if exists enseignants add constraint fk_enseignants_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists classes add constraint fk_classes_niveau foreign key (niveau_id) references niveaux;
alter table if exists classes add constraint fk_classes_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists classes add constraint fk_classes_enseignant_principal foreign key (enseignant_principal_id) references enseignants;
alter table if exists eleves add constraint fk_eleves_profil foreign key (profil_id) references profils;
alter table if exists eleves add constraint fk_eleves_classe foreign key (classe_id) references classes;
alter table if exists eleves add constraint fk_eleves_parent foreign key (parent_id) references parents;
alter table if exists eleves add constraint fk_eleves_parent_secondaire foreign key (parent_secondaire_id) references parents;
alter table if exists eleves add constraint fk_eleves_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists matieres add constraint fk_matieres_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists classes_matieres add constraint fk_cm_classe foreign key (classe_id) references classes;
alter table if exists classes_matieres add constraint fk_cm_matiere foreign key (matiere_id) references matieres;
alter table if exists classes_matieres add constraint fk_cm_enseignant foreign key (enseignant_id) references enseignants;
alter table if exists classes_matieres add constraint fk_cm_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists notes add constraint fk_notes_eleve foreign key (eleve_id) references eleves;
alter table if exists notes add constraint fk_notes_cm foreign key (classe_matiere_id) references classes_matieres;
alter table if exists notes add constraint fk_notes_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists notes add constraint fk_notes_cree_par foreign key (cree_par) references utilisateurs;
alter table if exists bulletins add constraint fk_bulletins_eleve foreign key (eleve_id) references eleves;
alter table if exists bulletins add constraint fk_bulletins_classe foreign key (classe_id) references classes;
alter table if exists bulletins add constraint fk_bulletins_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists presences add constraint fk_presences_eleve foreign key (eleve_id) references eleves;
alter table if exists presences add constraint fk_presences_cm foreign key (classe_matiere_id) references classes_matieres;
alter table if exists presences add constraint fk_presences_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists presences_enseignants add constraint fk_pe_enseignant foreign key (enseignant_id) references enseignants;
alter table if exists presences_enseignants add constraint fk_pe_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists frais_scolarite add constraint fk_frais_classe foreign key (classe_id) references classes;
alter table if exists frais_scolarite add constraint fk_frais_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists paiements add constraint fk_paiements_eleve foreign key (eleve_id) references eleves;
alter table if exists paiements add constraint fk_paiements_frais foreign key (frais_id) references frais_scolarite;
alter table if exists paiements add constraint fk_paiements_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists paiements add constraint fk_paiements_recu_par foreign key (recu_par) references utilisateurs;
alter table if exists emplois_du_temps add constraint fk_edt_cm foreign key (classe_matiere_id) references classes_matieres;
alter table if exists emplois_du_temps add constraint fk_edt_classe foreign key (classe_id) references classes;
alter table if exists emplois_du_temps add constraint fk_edt_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists notifications add constraint fk_notif_expediteur foreign key (expediteur_id) references utilisateurs;
alter table if exists notifications add constraint fk_notif_destinataire foreign key (destinataire_id) references utilisateurs;
alter table if exists notifications add constraint fk_notif_etablissement foreign key (etablissement_id) references etablissements;
alter table if exists journaux_activites add constraint fk_journal_utilisateur foreign key (utilisateur_id) references utilisateurs;
alter table if exists journaux_activites add constraint fk_journal_etablissement foreign key (etablissement_id) references etablissements;
